apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: it7tmzhdz-python 
  janus-idp.io/tekton: it7tmzhdz-python
  backstage.io/kubernetes-id: it7tmzhdz-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: it7tmzhdz-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml