apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: it7tmzhdz-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:1f388543811940f0cb99ea330ed9188320d42e5c@sha256:bf917e60de6bd7ae3ca3f5b0ad13d6ebeca21043e6c3e406b9a583599cbd368e
          name: container-image
